# Form implementation generated from reading ui file '.\ui\dc_asm_editor.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2055, 1141)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.asmField = LineAwareTextEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.asmField.setFont(font)
        self.asmField.setObjectName("asmField")
        self.horizontalLayout.addWidget(self.asmField)
        self.offsetField = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.offsetField.setReadOnly(True)
        self.offsetField.setObjectName("offsetField")
        self.horizontalLayout.addWidget(self.offsetField)
        self.hexField = LineAwareTextEdit(parent=self.centralwidget)
        self.hexField.setObjectName("hexField")
        self.horizontalLayout.addWidget(self.hexField)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2055, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DC Assembly Editor"))
        self.menuFile.setTitle(_translate("MainWindow", "File..."))
from line_aware_text_edit import LineAwareTextEdit
